# Generated by Django 4.0.5 on 2022-07-03 13:37

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('unlock_xp', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=1000)),
                ('sprite', models.ImageField(upload_to='static')),
                ('bought', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('experience', models.IntegerField(default=0)),
                ('currency', models.PositiveIntegerField(default=0)),
                ('avatar', models.URLField(default='https://miro.medium.com/max/720/1*W35QUSvGpcLuxPo3SRTH4w.png')),
                ('inventory', models.ManyToManyField(blank=True, to='bend_life_rpg.item')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default='Furniture Shop', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=250)),
                ('task_difficulty', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('is_complete', models.BooleanField(default=False)),
                ('task_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bend_life_rpg.player')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=50)),
                ('room_name', models.CharField(max_length=100)),
                ('shop_items', models.ManyToManyField(to='bend_life_rpg.item')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bend_life_rpg.player')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bend_life_rpg.shop'),
        ),
    ]
