# Generated by Django 4.0.5 on 2022-07-03 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bend_life_rpg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='user_id',
            new_name='room_owner',
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='shop_items',
            field=models.ManyToManyField(blank=True, to='bend_life_rpg.item'),
        ),
    ]
