# Generated by Django 4.0.5 on 2022-07-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bend_life_rpg', '0003_remove_item_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slot',
            field=models.CharField(choices=[('SOFA', 'Sofa'), ('BED', 'Bed'), ('RUG', 'Rug'), ('CABINET', 'Cabinet'), ('PICTURE_1', 'Picture1'), ('PICTURE_2', 'Picture2'), ('BATH', 'Bath'), ('FRIDGE', 'Fridge'), ('SINK', 'Sink'), ('OVEN', 'Oven'), ('TOILET', 'Toilet'), ('CHAIR', 'Chair')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(default='Room', max_length=100),
        ),
    ]
