# Generated by Django 4.0.5 on 2022-07-06 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bend_life_rpg', '0004_item_slot_alter_room_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='bought',
        ),
    ]
