# Generated by Django 4.0.5 on 2022-06-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bend_life_rpg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=250)),
                ('task_difficulty', models.IntegerField(default=1)),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='furniture',
            name='room_category',
            field=models.CharField(default='living roon', max_length=100),
        ),
    ]
